"use client";

import { useState } from "react";

import {
  defaultInvestigationModelId,
  isInvestigationModelId,
} from "@/lib/ai/model-registry";
import { parseInvestigationResult } from "@/lib/ai/output-schema";
import type {
  InvestigationModelId,
  InvestigationModelOption,
} from "@/lib/ai/types";
import type { DiagnosticCase } from "@/lib/diagnostics/types";
import type { InvestigationResult } from "@/lib/investigations/types";
import { buildValidationPlan } from "@/lib/validations/mock-data";
import type {
  ActionablePMReview,
  PMReview,
  ReviewDecision,
  ValidationPlan,
  ValidationPlanTemplate,
} from "@/lib/validations/types";

import { InvestigationDraft } from "./investigation-draft";
import { PMReviewPanel } from "./pm-review";
import { ValidationPlanCard } from "./validation-plan";

type InvestigationAssistantProps = {
  diagnosticCase: DiagnosticCase;
  models: InvestigationModelOption[];
  validationPlanTemplates: ValidationPlanTemplate[];
};

type JsonRecord = Record<string, unknown>;

function isRecord(value: unknown): value is JsonRecord {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

export function InvestigationAssistant({
  diagnosticCase,
  models,
  validationPlanTemplates,
}: InvestigationAssistantProps) {
  const [selectedModelId, setSelectedModelId] =
    useState<InvestigationModelId>(
      models[0]?.id ?? defaultInvestigationModelId,
    );
  const [usedModelId, setUsedModelId] =
    useState<InvestigationModelId | null>(null);
  const [result, setResult] = useState<InvestigationResult | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationError, setGenerationError] = useState<string | null>(null);
  const [fallbackMessage, setFallbackMessage] = useState<string | null>(null);
  const [isDraftVisible, setIsDraftVisible] = useState(false);
  const [decision, setDecision] = useState<ReviewDecision | null>(null);
  const [refinedHypothesis, setRefinedHypothesis] = useState("");
  const [note, setNote] = useState("");
  const [rejectionReason, setRejectionReason] = useState("");
  const [selectedValidationId, setSelectedValidationId] = useState("");
  const [confirmedReview, setConfirmedReview] = useState<PMReview | null>(null);
  const [validationPlan, setValidationPlan] = useState<ValidationPlan | null>(null);
  const [reviewError, setReviewError] = useState<string | null>(null);
  const workflowRegionId = result ? `investigation-workflow-${result.id}` : undefined;
  const usedModel = models.find((model) => model.id === usedModelId);
  const generationLabel = usedModel
    ? `Generated by ${usedModel.label}`
    : "Choose a model to create a draft";

  const validationOptions = result
    ? validationPlanTemplates.flatMap((template) => {
        const isRecommended = result.recommendedValidations.some(
          (recommendation) =>
            recommendation.validationId === template.nextValidationId,
        );
        const validation = diagnosticCase.nextValidations.find(
          (item) => item.id === template.nextValidationId,
        );

        if (!validation || !isRecommended) {
          return [];
        }

        return [validation];
      })
    : [];

  function resetReviewWorkflow() {
    setDecision(null);
    setRefinedHypothesis("");
    setNote("");
    setRejectionReason("");
    setSelectedValidationId("");
    setConfirmedReview(null);
    setValidationPlan(null);
    setReviewError(null);
  }

  async function handleGenerateInvestigation() {
    setIsGenerating(true);
    setGenerationError(null);
    setFallbackMessage(null);

    try {
      const response = await fetch("/api/investigations", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          diagnosticCaseId: diagnosticCase.id,
          modelId: selectedModelId,
        }),
      });
      const responseBody: unknown = await response.json();

      if (!response.ok || !isRecord(responseBody)) {
        throw new Error("Investigation generation failed.");
      }

      if (
        responseBody.requestedModelId !== selectedModelId ||
        !isInvestigationModelId(responseBody.usedModelId)
      ) {
        throw new Error("Investigation response metadata is invalid.");
      }

      const validatedResult = parseInvestigationResult(
        responseBody.result,
        diagnosticCase,
      );
      const fallback = isRecord(responseBody.fallback)
        ? responseBody.fallback
        : null;

      setResult(validatedResult);
      setUsedModelId(responseBody.usedModelId);
      setFallbackMessage(
        fallback && typeof fallback.message === "string"
          ? fallback.message
          : null,
      );
      setIsDraftVisible(true);
      resetReviewWorkflow();
    } catch {
      setGenerationError(
        "A validated investigation draft could not be generated. Try Mock Prototype.",
      );
    } finally {
      setIsGenerating(false);
    }
  }

  function handleDecisionChange(nextDecision: ReviewDecision) {
    setDecision(nextDecision);
    setConfirmedReview(null);
    setValidationPlan(null);
    setReviewError(null);

    if (nextDecision === "reject-suggestion") {
      setSelectedValidationId("");
    }
  }

  function handleConfirmReview() {
    if (!result || !decision) {
      return;
    }

    const reviewId = `pm-review-${result.id}`;
    const normalizedRefinement = refinedHypothesis.trim();
    const normalizedNote = note.trim() || null;

    if (decision === "reject-suggestion") {
      const normalizedReason = rejectionReason.trim();

      if (!normalizedReason) {
        setReviewError("Add a rejection reason before recording this decision.");
        return;
      }

      const review: PMReview = {
        id: reviewId,
        diagnosticCaseId: diagnosticCase.id,
        investigationResultId: result.id,
        sourceHypothesisId: result.workingHypothesis.id,
        decision,
        refinedHypothesis: null,
        note: normalizedNote,
        selectedValidationId: null,
        rejectionReason: normalizedReason,
        persistence: "session-only",
      };

      setConfirmedReview(review);
      setValidationPlan(null);
      setReviewError(null);
      return;
    }

    if (!selectedValidationId) {
      setReviewError("Select a validation before creating the plan.");
      return;
    }

    const template = validationPlanTemplates.find(
      (item) => item.nextValidationId === selectedValidationId,
    );

    if (!template) {
      setReviewError("No prototype plan template is available for this validation.");
      return;
    }

    const review: ActionablePMReview = {
      id: reviewId,
      diagnosticCaseId: diagnosticCase.id,
      investigationResultId: result.id,
      sourceHypothesisId: result.workingHypothesis.id,
      decision,
      refinedHypothesis:
        normalizedRefinement &&
        normalizedRefinement !== result.workingHypothesis.statement
          ? normalizedRefinement
          : null,
      note: normalizedNote,
      selectedValidationId,
      rejectionReason: null,
      persistence: "session-only",
    };
    const plan = buildValidationPlan(review, template, diagnosticCase, result);

    if (!plan) {
      setReviewError("The selected validation does not match this diagnostic case.");
      return;
    }

    setConfirmedReview(review);
    setValidationPlan(plan);
    setReviewError(null);
  }

  function handleEditReview() {
    setConfirmedReview(null);
    setValidationPlan(null);
    setReviewError(null);
  }

  function handleMarkAsPlanned() {
    setValidationPlan((currentPlan) =>
      currentPlan ? { ...currentPlan, status: "planned" } : currentPlan,
    );
  }

  return (
    <section
      className="rounded-xl border border-[#dce3fb] bg-white p-5 shadow-[0_1px_2px_rgba(16,24,40,0.02)] sm:p-6"
      aria-labelledby="investigation-assistant-title"
    >
      <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start">
        <div className="max-w-3xl">
          <div className="flex flex-wrap items-center gap-2">
            <p className="text-xs font-semibold uppercase tracking-[0.1em] text-[#3559e8]">
              AI Investigation Assistant
            </p>
            <span className="rounded-md bg-[#edf1ff] px-2 py-1 text-[10px] font-bold uppercase tracking-[0.08em] text-[#3559e8]">
              Prototype
            </span>
            <span className="rounded-md bg-[#f2f4f8] px-2 py-1 text-[10px] font-bold uppercase tracking-[0.08em] text-[#778196]">
              Mock result
            </span>
          </div>
          <h2
            id="investigation-assistant-title"
            className="mt-2 text-lg font-semibold tracking-[-0.025em] text-[#172033]"
          >
            Turn this diagnostic into a reviewable investigation draft
          </h2>
          <p className="mt-1.5 text-sm leading-6 text-[#68758b]">
            The draft is limited to this case and references its existing evidence. It proposes possible explanations and validation steps without making a causal conclusion.
          </p>
        </div>

        <div className="flex w-full flex-col gap-2 sm:w-auto sm:items-end">
          <label className="flex items-center gap-2 text-xs font-medium text-[#68758b]">
            <span>Model</span>
            <select
              value={selectedModelId}
              onChange={(event) => {
                const nextModelId = event.target.value;

                if (isInvestigationModelId(nextModelId)) {
                  setSelectedModelId(nextModelId);
                }
              }}
              disabled={isGenerating}
              className="min-h-9 rounded-md border border-[#dce3eb] bg-white px-2.5 text-xs font-semibold text-[#344054] outline-none transition-colors focus:border-[#3559e8] focus:ring-2 focus:ring-[#dce3fb] disabled:cursor-not-allowed disabled:bg-[#f7f8fa]"
              aria-label="Investigation model"
            >
              {models.map((model) => (
                <option key={model.id} value={model.id}>
                  {model.label}
                </option>
              ))}
            </select>
          </label>
          <button
            type="button"
            className="inline-flex min-h-10 w-full shrink-0 items-center justify-center rounded-lg bg-[#3559e8] px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-[#2949ca] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#3559e8] disabled:cursor-not-allowed disabled:bg-[#9cacef] sm:w-fit"
            disabled={isGenerating}
            aria-busy={isGenerating}
            onClick={handleGenerateInvestigation}
          >
            {isGenerating
              ? "Generating investigation draft..."
              : result
                ? "Create new investigation draft"
                : "Create investigation draft"}
          </button>
        </div>
      </div>

      <div className="mt-4 flex flex-wrap gap-2 text-[11px] text-[#778196]">
        <span className="rounded-md border border-[#e4e7ee] bg-[#fafbfc] px-2.5 py-1.5">
          Case: {diagnosticCase.title}
        </span>
        <span className="rounded-md border border-[#e4e7ee] bg-[#fafbfc] px-2.5 py-1.5">
          {result
            ? `${result.evidenceUsed.length} evidence references`
            : `${diagnosticCase.evidence.behaviorSignals.length + diagnosticCase.evidence.feedbackSignals.length} evidence signals`}
        </span>
        <span className="rounded-md border border-[#e4e7ee] bg-[#fafbfc] px-2.5 py-1.5">
          {generationLabel}
        </span>
      </div>

      {isGenerating ? (
        <p className="mt-4 text-sm font-medium text-[#3559e8]" role="status">
          Generating investigation draft...
        </p>
      ) : null}

      {generationError ? (
        <p
          className="mt-4 rounded-lg border border-[#f6d4d0] bg-[#fff7f6] px-3 py-2 text-sm text-[#b42318]"
          role="alert"
        >
          {generationError}
        </p>
      ) : null}

      {result && fallbackMessage ? (
        <p className="mt-4 rounded-lg border border-[#f2dfb0] bg-[#fffaf0] px-3 py-2 text-sm text-[#8a5b00]" role="status">
          <span className="font-semibold">Fallback to Mock Provider.</span>{" "}
          {fallbackMessage}
        </p>
      ) : null}

      {result && isDraftVisible ? (
        <div id={workflowRegionId}>
          <InvestigationDraft diagnosticCase={diagnosticCase} result={result} />
          <PMReviewPanel
            originalHypothesis={result.workingHypothesis.statement}
            decision={decision}
            refinedHypothesis={refinedHypothesis}
            note={note}
            rejectionReason={rejectionReason}
            selectedValidationId={selectedValidationId}
            validationOptions={validationOptions}
            confirmedReview={confirmedReview}
            error={reviewError}
            onDecisionChange={handleDecisionChange}
            onRefinedHypothesisChange={setRefinedHypothesis}
            onNoteChange={setNote}
            onRejectionReasonChange={setRejectionReason}
            onValidationChange={setSelectedValidationId}
            onConfirm={handleConfirmReview}
            onEdit={handleEditReview}
          />
          {validationPlan ? (
            <ValidationPlanCard
              plan={validationPlan}
              diagnosticCase={diagnosticCase}
              onMarkAsPlanned={handleMarkAsPlanned}
            />
          ) : null}
        </div>
      ) : null}
    </section>
  );
}
